skillMetadata:
  sections:
    - name: Snacks Settings
      fields:
        - name: snacks
          type: text
          label: Snacks
          value: "apples, Scoops, cheese, raisins, cookies, empty"
          placeholder: Comma-separated list of meals
